In [5]:
from dotenv import load_dotenv
import os


### Setup ###
# Load variables from .env file
load_dotenv()

# Base Path for image folder
numpy_folder: str = os.getenv("NUMPY_FOLDER")

In [6]:
from core.validation import get_valid_image_number

# Define numpy file path
img_number: str = get_valid_image_number()
numpy_file_path: str = os.path.join(numpy_folder, f"{img_number}.npy")

print(numpy_file_path)

/home/renato/Pictures/PIBIC/NumpyFiles/000.npy


In [12]:
# https://numpy.org/doc/stable/reference/generated/numpy.load.html#numpy.load

import numpy as np
from numpy import ndarray

# Load numpy file
numpy_file = np.load(numpy_file_path)

# Create future validation errors for this step

In [15]:
# https://numpy.org/doc/stable/reference/generated/numpy.array_split.html#numpy.array_split

# Split numpy file in a list of masks
masks: list[ndarray] = np.split(ary=numpy_file, indices_or_sections=18, axis=2)
print(masks)
print(f"Masks length: {len(masks)}")

[array([[[0],
        [0],
        [0],
        ...,
        [0],
        [0],
        [0]],

       [[0],
        [0],
        [0],
        ...,
        [0],
        [0],
        [0]],

       [[0],
        [0],
        [0],
        ...,
        [0],
        [0],
        [0]],

       ...,

       [[0],
        [0],
        [0],
        ...,
        [0],
        [0],
        [0]],

       [[0],
        [0],
        [0],
        ...,
        [0],
        [0],
        [0]],

       [[0],
        [0],
        [0],
        ...,
        [0],
        [0],
        [0]]], dtype=uint8), array([[[0],
        [0],
        [0],
        ...,
        [0],
        [0],
        [0]],

       [[0],
        [0],
        [0],
        ...,
        [0],
        [0],
        [0]],

       [[0],
        [0],
        [0],
        ...,
        [0],
        [0],
        [0]],

       ...,

       [[0],
        [0],
        [0],
        ...,
        [0],
        [0],
        [0]],

       [[0],
        [0],
   

In [19]:
# Test: Accessing a mask
print(masks[0])


[[[0]
  [0]
  [0]
  ...
  [0]
  [0]
  [0]]

 [[0]
  [0]
  [0]
  ...
  [0]
  [0]
  [0]]

 [[0]
  [0]
  [0]
  ...
  [0]
  [0]
  [0]]

 ...

 [[0]
  [0]
  [0]
  ...
  [0]
  [0]
  [0]]

 [[0]
  [0]
  [0]
  ...
  [0]
  [0]
  [0]]

 [[0]
  [0]
  [0]
  ...
  [0]
  [0]
  [0]]]
