In [1]:
from dotenv import load_dotenv
from core.validation import get_valid_image_number
import cv2 as cv
import matplotlib.pyplot as plt
from numpy import ndarray
import numpy as np
import os


### Setup ###
# Load variables from .env file
load_dotenv()

# Base Path for image folder
base_mask_folder: str = os.getenv("BASE_MASK_FOLDER")
output_folder: str = os.getenv("OUTPUT_FOLDER")

img_number: str = get_valid_image_number()
mask_path: str = os.path.join(base_mask_folder, f"{img_number}.png")

In [2]:
# Load and Convert Images
bgr_img = cv.imread(mask_path, 1)
hsv_img = cv.cvtColor(bgr_img, cv.COLOR_BGR2HSV)

# Define limits for Aqua Color >> HSV (R:255, G:82, B:70) to (R:255, G:255, B:90)
lower_bound = np.array([70, 82, 255]) #[H, S, V]
upper_bound = np.array([90, 255, 255]) #[H, S, V]

# Create binary mask
mask = cv.inRange(hsv_img, lower_bound, upper_bound)

In [3]:
# Inspect the Color Values for each Pixel
# cv.imshow("Inspect Image", mask)
# cv.waitKey(0)
# cv.destroyAllWindows()

qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in ""


In [5]:
# https://numpy.org/doc/stable/reference/generated/numpy.save.html

# Save as Numpy File
output_file: str = os.path.join(output_folder, f"{img_number}_mask_aqua")
np.save(output_file, mask) # Add .npy at the end

In [9]:
# Load and Print Numpy Matrix
numpy_file: str = f"{output_file}.npy"
with open(numpy_file, 'rb') as file:
    matrix: ndarray = np.load(file)
print(matrix)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
